"""empty message

Revision ID: a12eccd8099e
Revises: 
Create Date: 2018-05-28 15:42:28.460445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12eccd8099e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.create_table('Businesses',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('business_name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=60), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_index(op.f('ix_Businesses_business_name'), 'Businesses', ['business_name'], unique=True)
    op.create_index(op.f('ix_Businesses_category'), 'Businesses', ['category'], unique=False)
    op.create_index(op.f('ix_Businesses_location'), 'Businesses', ['location'], unique=False)
    op.create_table('Reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('review_name', sa.String(length=60), nullable=True),
    sa.Column('body', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['Businesses.business_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_Reviews_review_name'), 'Reviews', ['review_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Reviews_review_name'), table_name='Reviews')
    op.drop_table('Reviews')
    op.drop_index(op.f('ix_Businesses_location'), table_name='Businesses')
    op.drop_index(op.f('ix_Businesses_category'), table_name='Businesses')
    op.drop_index(op.f('ix_Businesses_business_name'), table_name='Businesses')
    op.drop_table('Businesses')
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    op.drop_table('Blacklist_tokens')
    # ### end Alembic commands ###
