"""empty message

Revision ID: b60dbe0f30d0
Revises: a12eccd8099e
Create Date: 2018-06-12 09:59:07.075935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60dbe0f30d0'
down_revision = 'a12eccd8099e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Reviews_review_name', table_name='Reviews')
    op.create_index(op.f('ix_Reviews_review_name'), 'Reviews', ['review_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Reviews_review_name'), table_name='Reviews')
    op.create_index('ix_Reviews_review_name', 'Reviews', ['review_name'], unique=True)
    # ### end Alembic commands ###
